# Generated by Django 2.2.4 on 2019-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_of_b',
            field=models.DateField(),
        ),
    ]
