# Generated by Django 2.2.4 on 2019-08-13 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20190813_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
