# Generated by Django 2.2.4 on 2019-08-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20190813_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
